$('#sendCoinsBtn').click(function(){$.ajax({url:'/api/coins/action/get-balance-to-send',type:'POST',success:function(data){let boughtBalance=data['boughtBalance'];let max=data['balance'];Swal.mixin({input:'text',title:LANG.coins.send,inputAttributes:{autocapitalize:'off',enterkeyhint:'next'},showCancelButton:true,cancelButtonText:LANG.general.cancel,confirmButtonText:LANG.shop.next+' &rarr;',progressSteps:['1','2','3'],allowOutsideClick:()=>!Swal.isLoading(),onOpen(popup){Flatland.initCoinInput(1,max,1);},preConfirm:(result)=>{if(Swal.getQueueStep()==='0'){return new Promise(function(resolve,reject){if(result===""){reject(LANG.coins.error.no_receiver);}
$.post('/api/coins/action/check-receiver',{receiver:result}).done(function(data){if(!data){reject(LANG.shop.cart.error.user_not_found);}
window.receiver=result;window.receiverUuid=data.uuid;window.receiverHeadUrl=data.head_url;resolve();}).fail(function(data){Swal.showValidationMessage(LANG.coins.error.contact_staff);reject();}).error(function(jqXHR,textStatus,errorThrown){Swal.showValidationMessage(LANG.coins.error.contact_staff);reject();});}).catch(function(jqXHR,textStatus,errorThrow){const errorString=LANG.general.error;Swal.showValidationMessage(`${errorString}: ${LANG.shop.cart.error.user_not_found}`)});}
if(Swal.getQueueStep()==='1'){result=parseInt(result.replace(".",""));if(result===""||result===0){Swal.showValidationMessage(LANG.coins.error.invalid_amount);return false;}
if(result>boughtBalance&&!['f7321d61-550a-4345-b46e-09a9657ef7f3','3a440181-e057-46ae-ad79-79873f03ddbe'].includes(window.receiverUuid)){Swal.showValidationMessage(LANG.coins.error.not_enough_coins.replace('%coins%',boughtBalance));return false;}
if(result>max){Swal.showValidationMessage(LANG.coins.error.too_much_coins);return false;}
window.amount=result;setTimeout(_=>{$('.sendCoinsConfirmation .receiver').text(window.receiver);$('.sendCoinsConfirmation img').attr('src',window.receiverHeadUrl).attr('alt',window.receiver);$('.sendCoinsConfirmation .amount').text(window.amount)},300)}
if(Swal.getQueueStep()==='2'){const receiver=window.receiver;const amount=window.amount;return new Promise(function(resolve,reject){$.ajax({url:'/api/move/coins',type:'POST',data:{receiver:receiver,amount:amount},success:function(data,textStatus,jqXHR){Swal.fire({title:'Success!',text:LANG['coins']['transfer_success'],icon:'success',allowEscapeKey:false,showCancelButton:false,confirmButtonColor:'#DD6B55',confirmButtonText:'Okay',cancelButtonText:LANG.general.cancel}).then(_=>{location.reload();});},error:function(data){const error=data.responseJSON;if(error.string==='verification_required'){const $id=parseInt(error.verification);Swal.fire({title:LANG['verification']['required'],text:LANG['verification']['description'],input:'text',inputAttributes:{autocapitalize:'off',placeholder:LANG['verification']['code'],autofocus:true,minlength:5,maxlength:5},showCancelButton:true,confirmButtonText:LANG['verification']['verify'],showLoaderOnConfirm:true,preConfirm:(key)=>{return $.ajax({url:'/api/move/coins',type:'POST',data:{receiver:receiver,amount:amount,verification:$id,key:key},success:function(data){Swal.fire({title:'Success!',text:LANG['coins']['transfer_success'],icon:'success',allowEscapeKey:false,showCancelButton:false,confirmButtonColor:'#DD6B55',confirmButtonText:'Okay',cancelButtonText:LANG.general.cancel}).then(_=>{location.reload();});},error:function(data){const $error=data.responseJSON.string;Swal.hideLoading();Swal.showValidationMessage(`Error: ${LANG['coins']['error'][$error].replace('%coins%',boughtBalance)}`);}});},allowOutsideClick:()=>!Swal.isLoading()});}
const $string=data.responseJSON.string;Swal.showValidationMessage(`Error: ${LANG['coins']['error'][$string].replace('%coins%',boughtBalance)}`);}});}).catch(err=>{const error=JSON.parse(err).string,errorMessage=LANG['coins']['error'][error].replace('%coins%',boughtBalance);Swal.showValidationMessage(`Error: ${errorMessage}`);});}}}).queue([{title:LANG.cosmetic_creator.name,text:LANG.shop.checkout.receiver,input:'text'},{title:LANG.shop.amount,text:'LabyCoins',customClass:{input:'creditInput'},input:'text',inputAttributes:{inputmode:'numeric',enterkeyhint:'next'},},{title:LANG.coins.confirmation,input:null,html:'<div class="sendCoinsConfirmation row"><div class="col-sm-7">'+
'<p>'+LANG.shop.checkout.receiver+': <span class="receiver"><i class="fas fa-spinner fa-spin"></i></span>'+
'</p><p>'+LANG.shop.amount+': <span class="amount"><i class="fas fa-spinner fa-spin"></i></span></p></div>'+
'<div class="col-sm-5"><img class="avatar" width="65" height="65" src="https://laby.net/texture/profile/head/8667ba71b85a4004af54457a9734eed7.png?size=64" alt="'+LANG.shop.checkout.receiver+'">'+
'</div></div>',confirmButtonText:LANG.coins.send,cancelButtonText:LANG.general.cancel}])},error:function(data,textStatus,errorThrown){Swal.fire("Sorry!",data["responseText"],"error");console.log(data);}});});$(document).ready(function(){$('#sendCoinsInputAmount').blur(function(){$(this).val(Math.round($(this).val()/10)*10);if(isNaN(parseFloat($(this).val())))$(this).val(10000);$(this).val(self.addCommas($(this).val()));});$('.locked').click(function(){Swal.fire(LANG['security']['move']['title'],LANG['security']['locked_text'],'error');});});